# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 15ceaa1cb0d67eb677f57b6bdf341c3636953ba20e15a1c454c94c05386643cf8972ce422a4c406e3f7c1b9904f7a94b3fd9a0dd33373fb0f598332935c08825

test:
  secret_key_base: 18ba29839d802eb60e55a2ef1313cce9fd81ca5679d7df9831fd485a545229971697d18a3b0548cad204837be8288661f7c91f7ea90a989f1080071e9a48ce31

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
